version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/plugin"
      schedule:
          interval: "weekly"
      groups:
          all-non-major:
              update-types:
                  - "minor"
                  - "patch"
    - package-ecosystem: "pip"
      directory: "/server"
      schedule:
          interval: "weekly"
      groups:
          all-non-major:
              update-types:
                  - "minor"
                  - "patch"
